name: Deploy Dist
on: [push,workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        run: | 
            echo 'cloning repo..'
            echo '${{toJson(github)}}'
            git clone https://github.com/${{github.repository}}.git