name: Deploy React to github pages

#on: [push, workflow_dispatch]
on:
  push:
    branches:
      - main
      - 'feature/**'
    paths-ignore:
      -'.github/workflows/*'
      - README.md
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache Dependencies,
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/packages-lock.json') }}
      - name: Print Node version
        run: node -v 
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test
      - name: Upload Dist Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist

        
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Dowloand Dist Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist
      - name: Get Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache Dependencies,
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/packages.lock.json') }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build  
      - name: Upload Dist Artifact
        uses: actions/upload-pages-artifact@v3
        with:
            name: dist-files
            path: files
  Deploy:
    # Add a dependency to the build job
    needs: build
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
        with:
            token: ${{secrets.GITHUB_TOKEN}}
